# Author
name: auycro

# Link
production_url : http://auycro.github.io
permalink: /blog/:year/:month/:day/:title

# Collections
collections:
  - posts
  - vimemos

# Conversion
markdown: kramdown

# Markdown
kramdown:
  input: GFM
  enable_coderay: true
