# Author
name: auycro

# Link
production_url : http://auycro.github.io
permalink: 
  - posts: /blog/:year/:month/:day/:title
  - vis: /vi-memo/:year/:month/:day/:title

# Conversion
markdown: kramdown

# Markdown
kramdown:
  input: GFM
  enable_coderay: true